let hiraganaArray = [
  ['あ', 'a', 'an <span>A</span>pple with a stem'],
  ['い', 'i', 'two <span>I\'s</span> side by side'],
  ['う', 'u', 'man kicked in the stomach and flying sideways while saying <span>\'Uuf\'</span>'],
  ['え', 'e', '<span>E</span>nergetic ninja running away'],
  ['お', 'o', 'uf<span>O</span> with an antenna'],
  ['か', 'ka', '<span>KA</span>r driving off a cliff'],
  ['き', 'ki', 'old fashioned <span>KEY</span>'],
  ['く', 'ku', 'beak of a <span>KUKU</span> bird'],
  ['け', 'ke', 'shape of a <span>KE</span>g'],
  ['こ', 'ko', '<span>KO</span>i fish swimming around each other'],
  ['さ', 'sa', '<span>SA</span>d face looking back at you'],
  ['し', 'shi', '<span>SHI</span>p\'s anchor'],
  ['す', 'su', 'pregnant woman <span>SOO</span>n expecting'],
  ['せ', 'se', 'two <span>SAI</span>ling ships passing each other'],
  ['そ', 'so', '<span>SEW</span>ing stitch'],
  ['た', 'ta', 'looks literally like <span>TA</span>'],
  ['ち', 'chi', '<span>CHEE</span>rleader mad at sa for being similar'],
  ['つ', 'tsu', '<span>TSU</span>nami wave'],
  ['て', 'te', 'dog\'s <span>TAI</span>l'],
  ['と', 'to', '<span>TO</span>e with a hangnail'],
  ['な', 'na', 'someone frying tu<span>NA</span>'],
  ['に', 'ni', 'looks like a <span>KNEE</span>'],
  ['ぬ', 'nu', '<span>NOO</span>dles with two chopsticks'],
  ['ね', 'ne', 's<span>NAI</span>l hiding behind a <span>NAI</span>l'],
  ['の', 'no', '<span>NO</span> entry sign'],
  ['は', 'ha/wa', 'capital <span>H</span> with a lowercase <span>A</span> under it = <span>HA</span>'],
  ['ひ', 'hi', 'smiling mouth saying <span>HEE HEE HEE</span>'],
  ['ふ', 'fu', 'nose smelling some <span>FU</span>mes'],
  ['へ', 'he', 'pointing to <span>HE</span>aven'],
  ['ほ', 'ho', '<span>HO</span> spelled on its side and a line underneath'],
  ['ま', 'ma', '<span>MA</span>n wearing a <span>MA</span>sk'],
  ['み', 'mi', 'like a musical note <span>MI</span>'],
  ['む', 'mu', 'a pierced cow\'s nose that says <span>MUUUU</span>'],
  ['め', 'me', 'same as nu but dropped some noodles and made a <span>ME</span>ss'],
  ['も', 'mo', 'ko<span>MO</span>do dragon with a long tail'],
  ['や', 'ya', 'birds on a wi<span>YA</span> outside your <span>YA</span>rd'],
  ['ゆ', 'yu', 'Jesus fish but spelled in Greek <span>YU</span>sus'],
  ['よ', 'yo', '<span>YO-YO</span> dangling from a finger'],
  ['ら', 'ra', '<span>RA</span>bbit bouncing away'],
  ['り', 'ri', 'looks like a <span>RI</span>ver. Longer right stroke. '],
  ['る', 'ru', '<span>RU</span>dder of a ship turning leaving a wake'],
  ['れ', 're', 'snake on the cross to <span>RE</span>vive patients'],
  ['ろ', 'ro', 'rear with a ship with less wake because it\'s being <span>RO</span>wed'],
  ['わ', 'wa', 'when moses struck the rock it burst forth with <span>WA</span>ter'],
  ['を', 'wo', '<span>WO</span>man walking across a street'],
  ['ん', 'n', 'looks like a letter <span>N</span>']
]
