let hiraganaArray = [
  ['あ', 'a', 'an Apple with a stem'],
  ['い', 'i', 'two I\'s side by side'],
  ['う', 'u', 'man kicked in the stomach and flying sideways while saying \'Uuf\''],
  ['え', 'e', 'Energetic ninja running away'],
  ['お', 'o', 'ufO with an antenna'],
  ['か', 'ka', 'KAr driving off a cliff'],
  ['き', 'ki', 'old fashioned KEY'],
  ['く', 'ku', 'beak of a KUku bird'],
  ['け', 'ke', 'shape of a KEg'],
  ['こ', 'ko', 'KOi fish swimming around each other'],
  ['さ', 'sa', 'SAd face looking back at you'],
  ['し', 'shi', 'SHIp\'s anchor'],
  ['す', 'su', 'pregnant woman SOOn expecting'],
  ['せ', 'se', 'two SAIling ships passing each other'],
  ['そ', 'so', 'SEWing stitch'],
  ['た', 'ta', 'looks literally like TA'],
  ['ち', 'chi', 'CHEERleader mad at sa for being similar'],
  ['つ', 'tsu', 'tsunami wave'],
  ['て', 'te', 'dog\'s TAIl'],
  ['と', 'to', 'TOe with a hangnail'],
  ['な', 'na', 'someone frying tuNA'],
  ['に', 'ni', 'looks like a KNEE'],
  ['ぬ', 'nu', 'NOOdles with two chopsticks'],
  ['ね', 'ne', 'sNAIl hiding behind a NAIl'],
  ['の', 'no', 'NO entry sign'],
  ['は', 'ha/wa', 'capital H with a lowercase A under it = HA'],
  ['ひ', 'hi', 'smiling mouth saying hi hi hi'],
  ['ふ', 'fu', 'nose smelling some FUmes'],
  ['へ', 'he', 'pointing to HEaven'],
  ['ほ', 'ho', 'HO spelled on its side and a line underneath'],
  ['ま', 'ma', 'MAn wearing a MAsk'],
  ['み', 'mi', 'like a musical note MI'],
  ['む', 'mu', 'a pierced cow\'s nose that says MUUUU'],
  ['め', 'me', 'same as nu but dropped some noodles and made a MEss'],
  ['も', 'mo', 'koMOdo dragon with a long tail'],
  ['や', 'ya', 'birds on a wiYA outside your YArd'],
  ['ゆ', 'yu', 'Jesus fish but spelled in Greek YUsus'],
  ['よ', 'yo', 'YO-YO dangling from a finger'],
  ['ら', 'ra', 'RAbbit bouncing away'],
  ['り', 'ri', 'looks like a RIver. Longer right stroke. '],
  ['る', 'ru', 'RUdder of a ship turning leaving a wake'],
  ['れ', 're', 'snake on the cross to REvive patients'],
  ['ろ', 'ro', 'rear with a ship with less wake because it\'s being ROwed'],
  ['わ', 'wa', ''],
  ['を', 'wo', 'WOman walking across a street'],
  ['ん', 'n', 'looks like a letter N']
]
